import { useMemo, useState } from 'react'
import { CircleAlert, Download, Info } from 'lucide-react'
import { Badge, Button, DataState, FilterBar, PageHeader, Pagination, SearchInput, Select, Table, Tooltip, useToast } from '../../components/ui'
import { balances, products, warehouses } from '../../data/demo'
import { formatNumber } from '../../lib/utils'
import { useCurrentWarehouse } from '../../app/App'

export default function InventoryPage() {
  const { warehouseId, setWarehouseId } = useCurrentWarehouse()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [page, setPage] = useState(1)
  const toast = useToast()
  const rows = useMemo(() => balances.map(balance => ({ ...balance, product: products.find(product => product.id === balance.productId)!, warehouse: warehouses.find(warehouse => warehouse.id === balance.warehouseId)! })).filter(row => (warehouseId === 'all' || row.warehouseId === warehouseId) && `${row.product.name} ${row.product.sku}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')) && (status === 'all' || (status === 'low' && row.quantity <= row.minimum) || (status === 'ok' && row.quantity > row.minimum))), [warehouseId, query, status])
  const pageCount = Math.max(1, Math.ceil(rows.length / 7))
  const visible = rows.slice((page - 1) * 7, page * 7)
  const total = rows.reduce((sum, row) => sum + row.quantity, 0)
  const reserved = rows.reduce((sum, row) => sum + row.reserved, 0)
  return <div className="page-enter"><PageHeader eyebrow="СКЛАД / ОСТАТКИ" title="Остатки" description="Актуальное наличие по товарам и складам." action={<Button onClick={() => toast('Экспорт остатков появится в следующем этапе')}><Download size={17} />Экспорт</Button>} /><div className="inventory-summary"><div><span>Фактический остаток</span><strong>{formatNumber(total)} <small>ед.</small></strong></div><div><span>В резерве</span><strong>{formatNumber(reserved)} <small>ед.</small></strong></div><div><span>Доступно</span><strong>{formatNumber(total - reserved)} <small>ед.</small></strong></div></div><div className="content-card"><div className="content-card-header"><div><h2>Остатки по складам</h2><p>Фактическое количество, резерв и доступный остаток</p></div><Tooltip content="Доступно = фактический остаток − резерв"><Button size="icon" variant="ghost" aria-label="Как рассчитывается доступный остаток"><Info size={17} /></Button></Tooltip></div><FilterBar><SearchInput className="filter-search" value={query} onChange={event => { setQuery(event.target.value); setPage(1) }} placeholder="Поиск товара или артикула" aria-label="Поиск остатков" /><div className="filter-selects"><Select value={warehouseId} onValueChange={value => { setWarehouseId(value); setPage(1) }} options={warehouses.map(item => ({ value: item.id, label: item.name }))} placeholder="Склад" /><Select value={status} onValueChange={value => { setStatus(value); setPage(1) }} options={[{ value: 'all', label: 'Все остатки' }, { value: 'low', label: 'Ниже минимума' }, { value: 'ok', label: 'В норме' }]} placeholder="Состояние" /></div></FilterBar><DataState status="ready" isEmpty={visible.length === 0}><Table className="inventory-table"><thead><tr><th>Товар</th><th>Артикул</th><th>Склад</th><th className="num-cell">Фактический остаток</th><th className="num-cell">Резерв</th><th className="num-cell">Доступно</th><th className="num-cell">Минимальный остаток</th></tr></thead><tbody>{visible.map(row => <tr key={row.id}><td className="product-name-cell"><strong>{row.product.name}</strong><small>{row.product.category}</small></td><td className="mono-cell">{row.product.sku}</td><td>{row.warehouse.name}</td><td className="num-cell quantity-cell">{formatNumber(row.quantity)}</td><td className="num-cell">{formatNumber(row.reserved)}</td><td className="num-cell"><strong>{formatNumber(row.quantity - row.reserved)}</strong></td><td className="num-cell">{row.quantity <= row.minimum ? <Badge tone="warning"><CircleAlert size={13} />{formatNumber(row.minimum)}</Badge> : formatNumber(row.minimum)}</td></tr>)}</tbody></Table><Pagination page={page} pageCount={pageCount} onChange={setPage} /></DataState></div><p className="demo-caption">Остатки демонстрационные. Формула доступного остатка уже применяется в интерфейсе.</p></div>
}
